---
# Container Python API, Kafka, Lambda consumer, via Terraform + CloudFormation
# github.com/sqlxpert/docker-python-openapi-kafka-terraform-cloudformation-aws
# GPLv3, Copyright Paul Marcelin

ignore_checks:
  - W2510
  # W2510: Lambda Memory Size parameters should use MinValue, MaxValue or
  #        AllowedValues: See comment about "underlying APIs"
