---
# Container Python API, Kafka, Lambda consumer, via Terraform + CloudFormation
# github.com/sqlxpert/docker-python-openapi-kafka-terraform-cloudformation-aws
# GPLv3, Copyright Paul Marcelin

ignored:

  - DL3041
  # As of 2025-09, this warning appears even though versions are specified in
  # `dnf install`!

  - DL3040
  - DL3042
  # docker build:
  #   https://docs.docker.com/build/cache/optimize/#use-cache-mounts
  # dnf:
  #   https://dnf.readthedocs.io/en/latest/command_ref.html#files
  #   https://dnf.readthedocs.io/en/latest/conf_ref.html#persistdir-label
  # pip:
  #   https://pip.pypa.io/en/stable/topics/caching/#default-paths
